config/routes.rb
Rails.application.routes.draw do
  get 'archives/index'
  resources :entries
  root to: "entries#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
    def day
        self.created_at.strftime("%b %e, %y")
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def index
    @entries = Entry.all.group_by(&:day)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:meal_type, :calories, :proteins, :carbohydrates, :fats)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/archives/index.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-half">
    <% @entries.each do |day, entries| %>
      <h3 class="is-size-4 has-text-weight-bold mb-4 has-text-centered">Entries for <%= day %></h3>

      <% entries.each do |entry| %>
        <%= link_to entry_path(entry) do %>
          <div class="card">
            <div class="card-content">
              <strong><%= entry.meal_type %></strong><br/>
              <%= entry.calories %> calories,
              <%= entry.proteins %>g protein,
              <%= entry.carbohydrates %>g carbohydrates,
              <%= entry.calories %>g fats
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/entries/_entry.html.erb
<div class="column is-one-third">
  <div class="card">
    <div class="card-content">
      <nav class="panel is-link">
        <p class="panel-heading">
          <%= entry.meal_type %>
        </p>

        <div class="panel-block">
          Calories: <%= entry.calories %>
        </div>

        <div class="panel-block">
          Proteins: <%= entry.proteins %>
        </div>

        <div class="panel-block">
          Carbohydrates: <%= entry.carbohydrates %>
        </div>

        <div class="panel-block">
          Fats: <%= entry.fats %>
        </div>
      </nav>

      <div>
        <p style="font-style: italic;">Logged <%= time_ago_in_words(entry.created_at) %> ago</p>
      </div>
    </div>
  </div>
</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :meal_type, style: "display: block" %>
    <%= form.text_field :meal_type %>
  </div>

  <div>
    <%= form.label :calories, style: "display: block" %>
    <%= form.number_field :calories %>
  </div>

  <div>
    <%= form.label :proteins, style: "display: block" %>
    <%= form.number_field :proteins %>
  </div>

  <div>
    <%= form.label :carbohydrates, style: "display: block" %>
    <%= form.number_field :carbohydrates %>
  </div>

  <div>
    <%= form.label :fats, style: "display: block" %>
    <%= form.number_field :fats %>
  </div>

  <div>
    <%= form.submit "Save", class: "button mt-5 is-primary" %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<% content_for :title do %>
  <%= @entry.meal_type %> &ndash; <%= DateTime.now.strftime('%B %e, %Y') %>
<% end %>

<div class="columns mt-6 is-centered">
  <div class="column is-mobile">
    <div class="card">
      <header class="card-header">
        <p class="is-size-3 card-header-title has-text-weight-bold mb-3 is-centered">Editing <%= @entry.meal_type %></p>
      </header>
      <div class="card-content">
        <%= form_with model: @entry, url: entry_path(@entry), method: :patch do |form| %>
          <div class="content">
            <div class="field">
              <label class="label">Meal Type</label>
              <div class="control">
                <%= form.text_field :meal_type, class: "input" %>
              </div>
            </div>
            <div class="field">
              <label class="label">Calories</label>
              <div class="control">
                <%= form.number_field :calories, class: "input" %>
              </div>
            </div>
            <div class="field">
              <label class="label">Proteins</label>
              <div class="control">
                <%= form.number_field :proteins, class: "input" %>
              </div>
            </div>
            <div class="field">
              <label class="label">Carbohydrates</label>
              <div class="control">
                <%= form.number_field :carbohydrates, class: "input" %>
              </div>
            </div>
            <div class="field">
              <label class="label">Fats</label>
              <div class="control">
                <%= form.number_field :fats, class: "input" %>
              </div>
            </div>
            
            <div class="field is-grouped is-grouped-centered">
              <div class="control">
                <%= form.submit "Save", class: "button is-success" %>
              </div>
              <div class="control">
                <%= link_to "Cancel", entries_path, class: "button is-danger" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <footer class="card-footer has-text-centered">
        <div class="buttons is-centered">
          <%= link_to "Back", entries_path, class: "button is-primary" %>
        </div>
      </footer>
    </div>
  </div>
</div>

app/views/entries/index.html.erb
<% content_for :title do %>
  Foodlog &ndash; <%= DateTime.now.strftime('%B %e, %Y') %>
<% end %>

<p style="color: green"><%= notice %></p>

<div id="entries" class="columns is-multiline is-centered">
  <% @entries.each do |entry| %>
    <div class="column is-one-third">
      <div class="card">
        <div class="card-content">
          <nav class="panel is-link">
            <p class="panel-heading">
              <%= entry.meal_type %>
            </p>

            <div class="panel-block">
              Calories: <%= entry.calories %>
            </div>

            <div class="panel-block">
              Proteins: <%= entry.proteins %>
            </div>

            <div class="panel-block">
              Carbohydrates: <%= entry.carbohydrates %>
            </div>

            <div class="panel-block">
              Fats: <%= entry.fats %>
            </div>
          </nav>

          <div>
            <p style="font-style: italic;">Logged <%= time_ago_in_words(entry.created_at) %> ago</p>
          </div>

          <div class="has-text-centered mt-2">
            <%= link_to "Show details", entry, class: "button is-primary is-small" %>
          </div>
<div class="columns is-centered mt-6">
<% link_to "View all entires", archives_index_path, class: "button is-link is-outlined is-centered" %>
</div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/entries/new.html.erb
<div class="columns mt-6 is-centered">
  <div class="column is-one-third">
    <div class="card">
      <header class="card-header">
        <p class="is-size-3 card-header-title has-text-weight-bold mb-3 is-centered">New entry</p>
      </header>
      <div class="card-content">
        <div class="content">
          <%= form_with model: @entry, url: entries_path do |form| %>
            <div class="field">
              <label class="label">Meal Type</label>
              <div class="control">
                <%= form.text_field :meal_type, class: "input" %>
              </div>
            </div>
            <div class="field">
              <label class="label">Calories</label>
              <div class="control">
                <%= form.number_field :calories, class: "input" %>
              </div>
            </div>
            <div class="field">
              <label class="label">Proteins</label>
              <div class="control">
                <%= form.number_field :proteins, class: "input" %>
              </div>
            </div>
            <div class="field">
              <label class="label">Carbohydrates</label>
              <div class="control">
                <%= form.number_field :carbohydrates, class: "input" %>
              </div>
            </div>
            <div class="field">
              <label class="label">Fats</label>
              <div class="control">
                <%= form.number_field :fats, class: "input" %>
              </div>
            </div>

            <div class="field is-grouped is-grouped-centered">
              <div class="control">
                <%= form.submit "Save", class: "button is-success" %>
              </div>
              <div class="control">
                <%= link_to "Cancel", entries_path, class: "button is-danger" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <footer class="card-footer">
        <div class="card-footer-item">
          <%= link_to "Back", entries_path, class: "button is-primary" %>
        </div>
      </footer>
    </div>
  </div>
</div>

<div class="columns is-centered mt-6">
<% link_to "View all entires", archives_index_path, class: "button is-link is-outlined is-centered" %>
</div>

app/views/entries/show.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title do %>
  <%= @entry.meal_type %> &ndash; <%= DateTime.now.strftime('%B %e, %Y') %>
<% end %>


<%= render @entry %>
<div class="columns mt-6 is-centered">
  <div class="columns card-footer is-centered">
    <div class="buttons">
      <%= link_to "Back", entries_path, class: "button is-primary" %>

      <%= link_to edit_entry_path(@entry), class: "button is-primary" do %>
        Edit
      <% end %>

      <%= button_to "Delete", @entry, method: :delete, class: "button is-danger" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Foodlog</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css" />
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <%= stylesheet_link_tag "application" , "data-turbo-track"=> "reload" %>
        <%= javascript_importmap_tags %>
</head>

<body>
  <%= render "shared/header" %>
    <% if notice.present? %>
      <div class="notification is-link is-light">
        <%= notice %>
      </div>
      <% end %>

        <% if alert.present? %>
          <div class="notification is-link is-light">
            <%= alert %>
          </div>
          <% end %>

            <div class="container">
              <%= yield %>
            </div>
</body>

</html>

app/views/shared/_header.html.erb
<section class="hero is-link is-small">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item" href="<%= root_path %>">
            <img src="<%= asset_path('logo.png') %>" alt="Logo">
          </a>
          <span class="navbar-burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
            <span class="navbar-item">
                <%= link_to "Create new entry", new_entry_path, class: "button is-success" %>
            </span>
          </div>
        </div>
      </div>
    </nav>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title">
        <% if content_for(:title) %>
        <%= yield :title %>
        <% else %>
            Foodlog            
        <% end %>
      </h1>
    </div>
  </div>

</section>
<div class="columns is-centered mt-6">
<%= link_to "Show all", archives_index_path, class: "button is-success"%>
</div>